#! /bin/sh
#
# $Id:$
#
# mha:       Starts the masterha_manager as Daemon
#
# Version:     1.0 
#
# chkconfig: 2345 90 10
# description: Start & Ends masterha_manager as a Daemon \
#
# processname: masterha_manager
# config: /etc/mha/

. /lib/lsb/init-functions

CLUSTER='group';
CONF=/etc/mha/${CLUSTER}.cnf  
LOGDIR=/var/log/mha/${CLUSTER}
LOGFILE=${LOGDIR}/${CLUSTER}.log  
WORKDIR=/data/mha/${CLUSTER}
export PATH=$PATH:/usr/local/bin

start () {
    echo -n "Starting ${CLUSTER}..."
    mkdir -p $LOGDIR
    command_ls=`nohup masterha_manager_app --conf=$CONF --manager_log=${LOGFILE} --manager_workdir=${WORKDIR} < /dev/null >> ${LOGFILE} 2>&1 &`
    if [[ $? -eq 0 ]]
    then 
        echo 'Success';
    else
        echo 'Failed';
        echo "Found more error information in file:${LOGFILE}";
    fi
}
stop () {
    echo -n "Stopping ${CLUSTER}..."
    masterha_stop --conf=${CONF}
}
status () {
    echo -n "Status of [MHA-$CLUSTER]:"
    masterha_check_status --conf=${CONF}

}
case $1 in
start)
    if status; then exit 0; fi
    start
    status && exit 0 || exit $?
    ;;
    stop)
    stop
    ;;
    reload)
    stop
    start
    ;;
    restart)
    stop
    start
    ;;
    status)
    status && exit 0 || exit $?
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
    ;;
    esac
    exit 0
